### ISSUE TITLE
Unicorn not deserializing different item versions

### ISSUE THREAD

**Issue by MrSnappingTurtle** [kamsar/Unicorn#188]
Hey,

I was recently working on creating different versions of items in another language. For this example, I made a Spanish version and removed the original English version. This resulted in me having the following `.yml` file:

```yml
---
ID: "8eb2cc77-bd5e-4555-b23a-8f3796cb858f"
Parent: "cd89c372-fcbf-44f0-aa9c-5b6153c68ddc"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: "/sitecore/content/somesite-com/spain"
DB: master
Languages:
- Language: "es-ES"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161110T150125
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
```

As you can see, it seems like it was serialized correctly, there is only one version, and it is the Spanish one. However, when the code was deserialized on another device, the Spanish version is missing, and only an English version is present:

![spanish](https://cloud.githubusercontent.com/assets/8148243/20203300/f8191024-a77a-11e6-8f5e-696ff4870076.PNG)

This doesn't seem to make sense as it is ignoring the contents of the `.yml` file. I saw the following output in the console:

```
[U] master:/sitecore/content/somesite-com/spain (8eb2cc77-bd5e-4555-b23a-8f3796cb858f)
> Orphaned version en#1 (source)
> Orphaned version en#1 (source)
> Orphaned version en#1 (source)
...
```

Any idea what might be going on? This is using Sitecore 7.5 and Unicorn 3.2.0. Thanks!
