### ISSUE TITLE
Issue with __Lock fields not being checked properly

### ISSUE THREAD

**Issue by MacDennis76** [kamsar/Unicorn#56]
Hi,

I am currently testing version 3.0-rc5 in combination with Sitecore 6.6.
All seems to work fine but I am now experiencing an issue with __Lock fields which seem to fail the check if the need to be updated.

I have the following item, taken from the Unicorn output:

```
[U] master:/sitecore/templates/Branches/User Defined/Websites/Horeca Toolbox/Quiz/Quiz root/$name/Winner slide (553fcbf5-1834-4707-8fcb-90c0eaf97bf9)
> Field __Lock - nl#1: Serialized , Source 
```

How many times I do a re-sync, it keeps throwing this message. It also does this with other __Lock fields of other items.

The serialized data contains:

```
- Language: nl
  Versions:
  - Version: 1
    Fields:
    - ID: 001dd393-96c5-490b-924a-b0f25cd9efd8
      # __Lock
      Value: <r />
```

It does have a value equal to <r /> but this is not present in the Unicorn output. Perhaps HTML tags are not displayed properly?

Data in target Sitecore environment before and after sync:

```
nl version of item: <r />
en version of item: 
en-gb version of item: this language version was not created
```

```
As you can see the nl version already contains <r /> and the serialized data does as well. But Unicorn still want to update this field with every sync.
```

Any ideas?

Kind regards,
Dennis
